version: '3.3' # optional since v1.27.0
services:
  front:
    tty: true
    image: calvinrahmat/front_blanja
    networks:
      - webnet
  webserver:
    image: calvinrahmat/nginx_blanja
    ports:
      - '80:80'
    networks:
      - webnet
networks:
  webnet:
volumes:
  database-data:
