version: '3.3' # optional since v1.27.0
services:
  front:
    tty: true
    image: calvinrahmat/front_blanja
    networks:
      - backend_webnet
networks:
  backend_webnet:
volumes:
  database-data:
